#Here, if necessary, more data is gathered and reformated into proper structure
#After reformating, contents of this file is transferred to data.py

[
    {"category": "Geography",
     "type": "boolean", "difficulty": "easy",
     "question": "Vatican City is a country.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},

    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Mario Kart 64&quot;, Waluigi is a playable character.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Luigi is taller than Mario?", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
     "question": "The Angry Video Game Nerd&#039;s alter ego is &quot;Board James&quot;.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Animals", "type": "boolean", "difficulty": "easy",
     "question": "A caterpillar has more muscles than humans do.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Doctor Who&quot;, the Doctor gets his TARDIS by stealing it.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In the &quot;S.T.A.L.K.E.R.&quot; series, the Freedom faction wishes to destroy the supernatural area known as  &quot;the Zone&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]}]
